name: 'Quantum Thinking '
favicon: null
layout_spectrum: 0.8907731478102505
typography_spectrum: 0.5830198337789625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8759240605868399
  lightness: 0.9173551795538515
  saturation: 0.9377838580403477
  rhythmicContrast: 0.3294649391900748
purpose: []
